# Generated by Django 5.1.4 on 2024-12-17 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_database',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_database',
            name='img_url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
