# Generated by Django 5.1.4 on 2024-12-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0002_user_database_created_at_user_database_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_database',
            name='slug',
            field=models.SlugField(default='slug-example', unique=True),
            preserve_default=False,
        ),
    ]
