# Generated by Django 5.1.4 on 2024-12-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0003_user_database_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
            ],
        ),
    ]
