# Generated by Django 5.1.4 on 2024-12-24 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0004_category_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_database',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='My_app.category_table'),
        ),
    ]
